CC = gcc

CFLAGS = -O3 -Wall -Werror -Wextra -Wnarrowing -Wconversion -Wwrite-strings -Wcast-qual -Wundef -Wstrict-prototypes -Wbad-function-cast -Wlogical-op -Wreturn-type

all: 11-Flock

11-Flock:
	$(CC) $(CFLAGS) 11-Flock.c -o 11-Flock.exe