# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/michael/Desktop/MIPT/CompScience/ComputerScience

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/michael/Desktop/MIPT/CompScience/ComputerScience

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/michael/Desktop/MIPT/CompScience/ComputerScience/CMakeFiles /home/michael/Desktop/MIPT/CompScience/ComputerScience/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/michael/Desktop/MIPT/CompScience/ComputerScience/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ./02-Write/02.1-Write

# Build rule for target.
./02-Write/02.1-Write: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ./02-Write/02.1-Write
.PHONY : ./02-Write/02.1-Write

# fast build rule for target.
./02-Write/02.1-Write/fast:
	$(MAKE) -f CMakeFiles/./02-Write/02.1-Write.dir/build.make CMakeFiles/./02-Write/02.1-Write.dir/build
.PHONY : ./02-Write/02.1-Write/fast

#=============================================================================
# Target rules for targets named ./03-CopyEntries/03.STAR-Copy

# Build rule for target.
./03-CopyEntries/03.STAR-Copy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ./03-CopyEntries/03.STAR-Copy
.PHONY : ./03-CopyEntries/03.STAR-Copy

# fast build rule for target.
./03-CopyEntries/03.STAR-Copy/fast:
	$(MAKE) -f CMakeFiles/./03-CopyEntries/03.STAR-Copy.dir/build.make CMakeFiles/./03-CopyEntries/03.STAR-Copy.dir/build
.PHONY : ./03-CopyEntries/03.STAR-Copy/fast

#=============================================================================
# Target rules for targets named ./01-Stat/01-Stat

# Build rule for target.
./01-Stat/01-Stat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ./01-Stat/01-Stat
.PHONY : ./01-Stat/01-Stat

# fast build rule for target.
./01-Stat/01-Stat/fast:
	$(MAKE) -f CMakeFiles/./01-Stat/01-Stat.dir/build.make CMakeFiles/./01-Stat/01-Stat.dir/build
.PHONY : ./01-Stat/01-Stat/fast

#=============================================================================
# Target rules for targets named ./06-Readdir/06.1-Readdir

# Build rule for target.
./06-Readdir/06.1-Readdir: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ./06-Readdir/06.1-Readdir
.PHONY : ./06-Readdir/06.1-Readdir

# fast build rule for target.
./06-Readdir/06.1-Readdir/fast:
	$(MAKE) -f CMakeFiles/./06-Readdir/06.1-Readdir.dir/build.make CMakeFiles/./06-Readdir/06.1-Readdir.dir/build
.PHONY : ./06-Readdir/06.1-Readdir/fast

#=============================================================================
# Target rules for targets named ./02-Write/02.2-Write

# Build rule for target.
./02-Write/02.2-Write: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ./02-Write/02.2-Write
.PHONY : ./02-Write/02.2-Write

# fast build rule for target.
./02-Write/02.2-Write/fast:
	$(MAKE) -f CMakeFiles/./02-Write/02.2-Write.dir/build.make CMakeFiles/./02-Write/02.2-Write.dir/build
.PHONY : ./02-Write/02.2-Write/fast

#=============================================================================
# Target rules for targets named ./06-Readdir/06.2-Readdir

# Build rule for target.
./06-Readdir/06.2-Readdir: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ./06-Readdir/06.2-Readdir
.PHONY : ./06-Readdir/06.2-Readdir

# fast build rule for target.
./06-Readdir/06.2-Readdir/fast:
	$(MAKE) -f CMakeFiles/./06-Readdir/06.2-Readdir.dir/build.make CMakeFiles/./06-Readdir/06.2-Readdir.dir/build
.PHONY : ./06-Readdir/06.2-Readdir/fast

#=============================================================================
# Target rules for targets named ./06-Readdir/06.3-Getdents

# Build rule for target.
./06-Readdir/06.3-Getdents: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ./06-Readdir/06.3-Getdents
.PHONY : ./06-Readdir/06.3-Getdents

# fast build rule for target.
./06-Readdir/06.3-Getdents/fast:
	$(MAKE) -f CMakeFiles/./06-Readdir/06.3-Getdents.dir/build.make CMakeFiles/./06-Readdir/06.3-Getdents.dir/build
.PHONY : ./06-Readdir/06.3-Getdents/fast

#=============================================================================
# Target rules for targets named ./03-CopyEntries/03.1-Copy

# Build rule for target.
./03-CopyEntries/03.1-Copy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ./03-CopyEntries/03.1-Copy
.PHONY : ./03-CopyEntries/03.1-Copy

# fast build rule for target.
./03-CopyEntries/03.1-Copy/fast:
	$(MAKE) -f CMakeFiles/./03-CopyEntries/03.1-Copy.dir/build.make CMakeFiles/./03-CopyEntries/03.1-Copy.dir/build
.PHONY : ./03-CopyEntries/03.1-Copy/fast

#=============================================================================
# Target rules for targets named ./03-CopyEntries/03.2-Copy

# Build rule for target.
./03-CopyEntries/03.2-Copy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ./03-CopyEntries/03.2-Copy
.PHONY : ./03-CopyEntries/03.2-Copy

# fast build rule for target.
./03-CopyEntries/03.2-Copy/fast:
	$(MAKE) -f CMakeFiles/./03-CopyEntries/03.2-Copy.dir/build.make CMakeFiles/./03-CopyEntries/03.2-Copy.dir/build
.PHONY : ./03-CopyEntries/03.2-Copy/fast

#=============================================================================
# Target rules for targets named ./05-CopyOwn/05-Fchown

# Build rule for target.
./05-CopyOwn/05-Fchown: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ./05-CopyOwn/05-Fchown
.PHONY : ./05-CopyOwn/05-Fchown

# fast build rule for target.
./05-CopyOwn/05-Fchown/fast:
	$(MAKE) -f CMakeFiles/./05-CopyOwn/05-Fchown.dir/build.make CMakeFiles/./05-CopyOwn/05-Fchown.dir/build
.PHONY : ./05-CopyOwn/05-Fchown/fast

#=============================================================================
# Target rules for targets named ./04-CopyPerm/04-Copy

# Build rule for target.
./04-CopyPerm/04-Copy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ./04-CopyPerm/04-Copy
.PHONY : ./04-CopyPerm/04-Copy

# fast build rule for target.
./04-CopyPerm/04-Copy/fast:
	$(MAKE) -f CMakeFiles/./04-CopyPerm/04-Copy.dir/build.make CMakeFiles/./04-CopyPerm/04-Copy.dir/build
.PHONY : ./04-CopyPerm/04-Copy/fast

#=============================================================================
# Target rules for targets named ./06-Readdir/06.4-Recursive6.2

# Build rule for target.
./06-Readdir/06.4-Recursive6.2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ./06-Readdir/06.4-Recursive6.2
.PHONY : ./06-Readdir/06.4-Recursive6.2

# fast build rule for target.
./06-Readdir/06.4-Recursive6.2/fast:
	$(MAKE) -f CMakeFiles/./06-Readdir/06.4-Recursive6.2.dir/build.make CMakeFiles/./06-Readdir/06.4-Recursive6.2.dir/build
.PHONY : ./06-Readdir/06.4-Recursive6.2/fast

01-Stat/01-Stat.o: 01-Stat/01-Stat.c.o

.PHONY : 01-Stat/01-Stat.o

# target to build an object file
01-Stat/01-Stat.c.o:
	$(MAKE) -f CMakeFiles/./01-Stat/01-Stat.dir/build.make CMakeFiles/./01-Stat/01-Stat.dir/01-Stat/01-Stat.c.o
.PHONY : 01-Stat/01-Stat.c.o

01-Stat/01-Stat.i: 01-Stat/01-Stat.c.i

.PHONY : 01-Stat/01-Stat.i

# target to preprocess a source file
01-Stat/01-Stat.c.i:
	$(MAKE) -f CMakeFiles/./01-Stat/01-Stat.dir/build.make CMakeFiles/./01-Stat/01-Stat.dir/01-Stat/01-Stat.c.i
.PHONY : 01-Stat/01-Stat.c.i

01-Stat/01-Stat.s: 01-Stat/01-Stat.c.s

.PHONY : 01-Stat/01-Stat.s

# target to generate assembly for a file
01-Stat/01-Stat.c.s:
	$(MAKE) -f CMakeFiles/./01-Stat/01-Stat.dir/build.make CMakeFiles/./01-Stat/01-Stat.dir/01-Stat/01-Stat.c.s
.PHONY : 01-Stat/01-Stat.c.s

02-Write/02.1-Write.o: 02-Write/02.1-Write.c.o

.PHONY : 02-Write/02.1-Write.o

# target to build an object file
02-Write/02.1-Write.c.o:
	$(MAKE) -f CMakeFiles/./02-Write/02.1-Write.dir/build.make CMakeFiles/./02-Write/02.1-Write.dir/02-Write/02.1-Write.c.o
.PHONY : 02-Write/02.1-Write.c.o

02-Write/02.1-Write.i: 02-Write/02.1-Write.c.i

.PHONY : 02-Write/02.1-Write.i

# target to preprocess a source file
02-Write/02.1-Write.c.i:
	$(MAKE) -f CMakeFiles/./02-Write/02.1-Write.dir/build.make CMakeFiles/./02-Write/02.1-Write.dir/02-Write/02.1-Write.c.i
.PHONY : 02-Write/02.1-Write.c.i

02-Write/02.1-Write.s: 02-Write/02.1-Write.c.s

.PHONY : 02-Write/02.1-Write.s

# target to generate assembly for a file
02-Write/02.1-Write.c.s:
	$(MAKE) -f CMakeFiles/./02-Write/02.1-Write.dir/build.make CMakeFiles/./02-Write/02.1-Write.dir/02-Write/02.1-Write.c.s
.PHONY : 02-Write/02.1-Write.c.s

02-Write/02.2-Write.o: 02-Write/02.2-Write.c.o

.PHONY : 02-Write/02.2-Write.o

# target to build an object file
02-Write/02.2-Write.c.o:
	$(MAKE) -f CMakeFiles/./02-Write/02.2-Write.dir/build.make CMakeFiles/./02-Write/02.2-Write.dir/02-Write/02.2-Write.c.o
.PHONY : 02-Write/02.2-Write.c.o

02-Write/02.2-Write.i: 02-Write/02.2-Write.c.i

.PHONY : 02-Write/02.2-Write.i

# target to preprocess a source file
02-Write/02.2-Write.c.i:
	$(MAKE) -f CMakeFiles/./02-Write/02.2-Write.dir/build.make CMakeFiles/./02-Write/02.2-Write.dir/02-Write/02.2-Write.c.i
.PHONY : 02-Write/02.2-Write.c.i

02-Write/02.2-Write.s: 02-Write/02.2-Write.c.s

.PHONY : 02-Write/02.2-Write.s

# target to generate assembly for a file
02-Write/02.2-Write.c.s:
	$(MAKE) -f CMakeFiles/./02-Write/02.2-Write.dir/build.make CMakeFiles/./02-Write/02.2-Write.dir/02-Write/02.2-Write.c.s
.PHONY : 02-Write/02.2-Write.c.s

03-CopyEntries/03.1-Copy.o: 03-CopyEntries/03.1-Copy.c.o

.PHONY : 03-CopyEntries/03.1-Copy.o

# target to build an object file
03-CopyEntries/03.1-Copy.c.o:
	$(MAKE) -f CMakeFiles/./03-CopyEntries/03.1-Copy.dir/build.make CMakeFiles/./03-CopyEntries/03.1-Copy.dir/03-CopyEntries/03.1-Copy.c.o
.PHONY : 03-CopyEntries/03.1-Copy.c.o

03-CopyEntries/03.1-Copy.i: 03-CopyEntries/03.1-Copy.c.i

.PHONY : 03-CopyEntries/03.1-Copy.i

# target to preprocess a source file
03-CopyEntries/03.1-Copy.c.i:
	$(MAKE) -f CMakeFiles/./03-CopyEntries/03.1-Copy.dir/build.make CMakeFiles/./03-CopyEntries/03.1-Copy.dir/03-CopyEntries/03.1-Copy.c.i
.PHONY : 03-CopyEntries/03.1-Copy.c.i

03-CopyEntries/03.1-Copy.s: 03-CopyEntries/03.1-Copy.c.s

.PHONY : 03-CopyEntries/03.1-Copy.s

# target to generate assembly for a file
03-CopyEntries/03.1-Copy.c.s:
	$(MAKE) -f CMakeFiles/./03-CopyEntries/03.1-Copy.dir/build.make CMakeFiles/./03-CopyEntries/03.1-Copy.dir/03-CopyEntries/03.1-Copy.c.s
.PHONY : 03-CopyEntries/03.1-Copy.c.s

03-CopyEntries/03.2-Copy.o: 03-CopyEntries/03.2-Copy.c.o

.PHONY : 03-CopyEntries/03.2-Copy.o

# target to build an object file
03-CopyEntries/03.2-Copy.c.o:
	$(MAKE) -f CMakeFiles/./03-CopyEntries/03.2-Copy.dir/build.make CMakeFiles/./03-CopyEntries/03.2-Copy.dir/03-CopyEntries/03.2-Copy.c.o
.PHONY : 03-CopyEntries/03.2-Copy.c.o

03-CopyEntries/03.2-Copy.i: 03-CopyEntries/03.2-Copy.c.i

.PHONY : 03-CopyEntries/03.2-Copy.i

# target to preprocess a source file
03-CopyEntries/03.2-Copy.c.i:
	$(MAKE) -f CMakeFiles/./03-CopyEntries/03.2-Copy.dir/build.make CMakeFiles/./03-CopyEntries/03.2-Copy.dir/03-CopyEntries/03.2-Copy.c.i
.PHONY : 03-CopyEntries/03.2-Copy.c.i

03-CopyEntries/03.2-Copy.s: 03-CopyEntries/03.2-Copy.c.s

.PHONY : 03-CopyEntries/03.2-Copy.s

# target to generate assembly for a file
03-CopyEntries/03.2-Copy.c.s:
	$(MAKE) -f CMakeFiles/./03-CopyEntries/03.2-Copy.dir/build.make CMakeFiles/./03-CopyEntries/03.2-Copy.dir/03-CopyEntries/03.2-Copy.c.s
.PHONY : 03-CopyEntries/03.2-Copy.c.s

03-CopyEntries/03.STAR-Copy.o: 03-CopyEntries/03.STAR-Copy.c.o

.PHONY : 03-CopyEntries/03.STAR-Copy.o

# target to build an object file
03-CopyEntries/03.STAR-Copy.c.o:
	$(MAKE) -f CMakeFiles/./03-CopyEntries/03.STAR-Copy.dir/build.make CMakeFiles/./03-CopyEntries/03.STAR-Copy.dir/03-CopyEntries/03.STAR-Copy.c.o
.PHONY : 03-CopyEntries/03.STAR-Copy.c.o

03-CopyEntries/03.STAR-Copy.i: 03-CopyEntries/03.STAR-Copy.c.i

.PHONY : 03-CopyEntries/03.STAR-Copy.i

# target to preprocess a source file
03-CopyEntries/03.STAR-Copy.c.i:
	$(MAKE) -f CMakeFiles/./03-CopyEntries/03.STAR-Copy.dir/build.make CMakeFiles/./03-CopyEntries/03.STAR-Copy.dir/03-CopyEntries/03.STAR-Copy.c.i
.PHONY : 03-CopyEntries/03.STAR-Copy.c.i

03-CopyEntries/03.STAR-Copy.s: 03-CopyEntries/03.STAR-Copy.c.s

.PHONY : 03-CopyEntries/03.STAR-Copy.s

# target to generate assembly for a file
03-CopyEntries/03.STAR-Copy.c.s:
	$(MAKE) -f CMakeFiles/./03-CopyEntries/03.STAR-Copy.dir/build.make CMakeFiles/./03-CopyEntries/03.STAR-Copy.dir/03-CopyEntries/03.STAR-Copy.c.s
.PHONY : 03-CopyEntries/03.STAR-Copy.c.s

04-CopyPerm/04-Copy.o: 04-CopyPerm/04-Copy.c.o

.PHONY : 04-CopyPerm/04-Copy.o

# target to build an object file
04-CopyPerm/04-Copy.c.o:
	$(MAKE) -f CMakeFiles/./04-CopyPerm/04-Copy.dir/build.make CMakeFiles/./04-CopyPerm/04-Copy.dir/04-CopyPerm/04-Copy.c.o
.PHONY : 04-CopyPerm/04-Copy.c.o

04-CopyPerm/04-Copy.i: 04-CopyPerm/04-Copy.c.i

.PHONY : 04-CopyPerm/04-Copy.i

# target to preprocess a source file
04-CopyPerm/04-Copy.c.i:
	$(MAKE) -f CMakeFiles/./04-CopyPerm/04-Copy.dir/build.make CMakeFiles/./04-CopyPerm/04-Copy.dir/04-CopyPerm/04-Copy.c.i
.PHONY : 04-CopyPerm/04-Copy.c.i

04-CopyPerm/04-Copy.s: 04-CopyPerm/04-Copy.c.s

.PHONY : 04-CopyPerm/04-Copy.s

# target to generate assembly for a file
04-CopyPerm/04-Copy.c.s:
	$(MAKE) -f CMakeFiles/./04-CopyPerm/04-Copy.dir/build.make CMakeFiles/./04-CopyPerm/04-Copy.dir/04-CopyPerm/04-Copy.c.s
.PHONY : 04-CopyPerm/04-Copy.c.s

05-CopyOwn/05-Fchown.o: 05-CopyOwn/05-Fchown.c.o

.PHONY : 05-CopyOwn/05-Fchown.o

# target to build an object file
05-CopyOwn/05-Fchown.c.o:
	$(MAKE) -f CMakeFiles/./05-CopyOwn/05-Fchown.dir/build.make CMakeFiles/./05-CopyOwn/05-Fchown.dir/05-CopyOwn/05-Fchown.c.o
.PHONY : 05-CopyOwn/05-Fchown.c.o

05-CopyOwn/05-Fchown.i: 05-CopyOwn/05-Fchown.c.i

.PHONY : 05-CopyOwn/05-Fchown.i

# target to preprocess a source file
05-CopyOwn/05-Fchown.c.i:
	$(MAKE) -f CMakeFiles/./05-CopyOwn/05-Fchown.dir/build.make CMakeFiles/./05-CopyOwn/05-Fchown.dir/05-CopyOwn/05-Fchown.c.i
.PHONY : 05-CopyOwn/05-Fchown.c.i

05-CopyOwn/05-Fchown.s: 05-CopyOwn/05-Fchown.c.s

.PHONY : 05-CopyOwn/05-Fchown.s

# target to generate assembly for a file
05-CopyOwn/05-Fchown.c.s:
	$(MAKE) -f CMakeFiles/./05-CopyOwn/05-Fchown.dir/build.make CMakeFiles/./05-CopyOwn/05-Fchown.dir/05-CopyOwn/05-Fchown.c.s
.PHONY : 05-CopyOwn/05-Fchown.c.s

06-Readdir/06.1-Readdir.o: 06-Readdir/06.1-Readdir.c.o

.PHONY : 06-Readdir/06.1-Readdir.o

# target to build an object file
06-Readdir/06.1-Readdir.c.o:
	$(MAKE) -f CMakeFiles/./06-Readdir/06.1-Readdir.dir/build.make CMakeFiles/./06-Readdir/06.1-Readdir.dir/06-Readdir/06.1-Readdir.c.o
.PHONY : 06-Readdir/06.1-Readdir.c.o

06-Readdir/06.1-Readdir.i: 06-Readdir/06.1-Readdir.c.i

.PHONY : 06-Readdir/06.1-Readdir.i

# target to preprocess a source file
06-Readdir/06.1-Readdir.c.i:
	$(MAKE) -f CMakeFiles/./06-Readdir/06.1-Readdir.dir/build.make CMakeFiles/./06-Readdir/06.1-Readdir.dir/06-Readdir/06.1-Readdir.c.i
.PHONY : 06-Readdir/06.1-Readdir.c.i

06-Readdir/06.1-Readdir.s: 06-Readdir/06.1-Readdir.c.s

.PHONY : 06-Readdir/06.1-Readdir.s

# target to generate assembly for a file
06-Readdir/06.1-Readdir.c.s:
	$(MAKE) -f CMakeFiles/./06-Readdir/06.1-Readdir.dir/build.make CMakeFiles/./06-Readdir/06.1-Readdir.dir/06-Readdir/06.1-Readdir.c.s
.PHONY : 06-Readdir/06.1-Readdir.c.s

06-Readdir/06.2-Readdir.o: 06-Readdir/06.2-Readdir.c.o

.PHONY : 06-Readdir/06.2-Readdir.o

# target to build an object file
06-Readdir/06.2-Readdir.c.o:
	$(MAKE) -f CMakeFiles/./06-Readdir/06.2-Readdir.dir/build.make CMakeFiles/./06-Readdir/06.2-Readdir.dir/06-Readdir/06.2-Readdir.c.o
.PHONY : 06-Readdir/06.2-Readdir.c.o

06-Readdir/06.2-Readdir.i: 06-Readdir/06.2-Readdir.c.i

.PHONY : 06-Readdir/06.2-Readdir.i

# target to preprocess a source file
06-Readdir/06.2-Readdir.c.i:
	$(MAKE) -f CMakeFiles/./06-Readdir/06.2-Readdir.dir/build.make CMakeFiles/./06-Readdir/06.2-Readdir.dir/06-Readdir/06.2-Readdir.c.i
.PHONY : 06-Readdir/06.2-Readdir.c.i

06-Readdir/06.2-Readdir.s: 06-Readdir/06.2-Readdir.c.s

.PHONY : 06-Readdir/06.2-Readdir.s

# target to generate assembly for a file
06-Readdir/06.2-Readdir.c.s:
	$(MAKE) -f CMakeFiles/./06-Readdir/06.2-Readdir.dir/build.make CMakeFiles/./06-Readdir/06.2-Readdir.dir/06-Readdir/06.2-Readdir.c.s
.PHONY : 06-Readdir/06.2-Readdir.c.s

06-Readdir/06.3-Getdents.o: 06-Readdir/06.3-Getdents.c.o

.PHONY : 06-Readdir/06.3-Getdents.o

# target to build an object file
06-Readdir/06.3-Getdents.c.o:
	$(MAKE) -f CMakeFiles/./06-Readdir/06.3-Getdents.dir/build.make CMakeFiles/./06-Readdir/06.3-Getdents.dir/06-Readdir/06.3-Getdents.c.o
.PHONY : 06-Readdir/06.3-Getdents.c.o

06-Readdir/06.3-Getdents.i: 06-Readdir/06.3-Getdents.c.i

.PHONY : 06-Readdir/06.3-Getdents.i

# target to preprocess a source file
06-Readdir/06.3-Getdents.c.i:
	$(MAKE) -f CMakeFiles/./06-Readdir/06.3-Getdents.dir/build.make CMakeFiles/./06-Readdir/06.3-Getdents.dir/06-Readdir/06.3-Getdents.c.i
.PHONY : 06-Readdir/06.3-Getdents.c.i

06-Readdir/06.3-Getdents.s: 06-Readdir/06.3-Getdents.c.s

.PHONY : 06-Readdir/06.3-Getdents.s

# target to generate assembly for a file
06-Readdir/06.3-Getdents.c.s:
	$(MAKE) -f CMakeFiles/./06-Readdir/06.3-Getdents.dir/build.make CMakeFiles/./06-Readdir/06.3-Getdents.dir/06-Readdir/06.3-Getdents.c.s
.PHONY : 06-Readdir/06.3-Getdents.c.s

06-Readdir/06.4-Recursive6.2.o: 06-Readdir/06.4-Recursive6.2.c.o

.PHONY : 06-Readdir/06.4-Recursive6.2.o

# target to build an object file
06-Readdir/06.4-Recursive6.2.c.o:
	$(MAKE) -f CMakeFiles/./06-Readdir/06.4-Recursive6.2.dir/build.make CMakeFiles/./06-Readdir/06.4-Recursive6.2.dir/06-Readdir/06.4-Recursive6.2.c.o
.PHONY : 06-Readdir/06.4-Recursive6.2.c.o

06-Readdir/06.4-Recursive6.2.i: 06-Readdir/06.4-Recursive6.2.c.i

.PHONY : 06-Readdir/06.4-Recursive6.2.i

# target to preprocess a source file
06-Readdir/06.4-Recursive6.2.c.i:
	$(MAKE) -f CMakeFiles/./06-Readdir/06.4-Recursive6.2.dir/build.make CMakeFiles/./06-Readdir/06.4-Recursive6.2.dir/06-Readdir/06.4-Recursive6.2.c.i
.PHONY : 06-Readdir/06.4-Recursive6.2.c.i

06-Readdir/06.4-Recursive6.2.s: 06-Readdir/06.4-Recursive6.2.c.s

.PHONY : 06-Readdir/06.4-Recursive6.2.s

# target to generate assembly for a file
06-Readdir/06.4-Recursive6.2.c.s:
	$(MAKE) -f CMakeFiles/./06-Readdir/06.4-Recursive6.2.dir/build.make CMakeFiles/./06-Readdir/06.4-Recursive6.2.dir/06-Readdir/06.4-Recursive6.2.c.s
.PHONY : 06-Readdir/06.4-Recursive6.2.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... ./02-Write/02.1-Write"
	@echo "... ./03-CopyEntries/03.STAR-Copy"
	@echo "... ./01-Stat/01-Stat"
	@echo "... ./06-Readdir/06.1-Readdir"
	@echo "... ./02-Write/02.2-Write"
	@echo "... ./06-Readdir/06.2-Readdir"
	@echo "... ./06-Readdir/06.3-Getdents"
	@echo "... ./03-CopyEntries/03.1-Copy"
	@echo "... ./03-CopyEntries/03.2-Copy"
	@echo "... ./05-CopyOwn/05-Fchown"
	@echo "... ./04-CopyPerm/04-Copy"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... ./06-Readdir/06.4-Recursive6.2"
	@echo "... 01-Stat/01-Stat.o"
	@echo "... 01-Stat/01-Stat.i"
	@echo "... 01-Stat/01-Stat.s"
	@echo "... 02-Write/02.1-Write.o"
	@echo "... 02-Write/02.1-Write.i"
	@echo "... 02-Write/02.1-Write.s"
	@echo "... 02-Write/02.2-Write.o"
	@echo "... 02-Write/02.2-Write.i"
	@echo "... 02-Write/02.2-Write.s"
	@echo "... 03-CopyEntries/03.1-Copy.o"
	@echo "... 03-CopyEntries/03.1-Copy.i"
	@echo "... 03-CopyEntries/03.1-Copy.s"
	@echo "... 03-CopyEntries/03.2-Copy.o"
	@echo "... 03-CopyEntries/03.2-Copy.i"
	@echo "... 03-CopyEntries/03.2-Copy.s"
	@echo "... 03-CopyEntries/03.STAR-Copy.o"
	@echo "... 03-CopyEntries/03.STAR-Copy.i"
	@echo "... 03-CopyEntries/03.STAR-Copy.s"
	@echo "... 04-CopyPerm/04-Copy.o"
	@echo "... 04-CopyPerm/04-Copy.i"
	@echo "... 04-CopyPerm/04-Copy.s"
	@echo "... 05-CopyOwn/05-Fchown.o"
	@echo "... 05-CopyOwn/05-Fchown.i"
	@echo "... 05-CopyOwn/05-Fchown.s"
	@echo "... 06-Readdir/06.1-Readdir.o"
	@echo "... 06-Readdir/06.1-Readdir.i"
	@echo "... 06-Readdir/06.1-Readdir.s"
	@echo "... 06-Readdir/06.2-Readdir.o"
	@echo "... 06-Readdir/06.2-Readdir.i"
	@echo "... 06-Readdir/06.2-Readdir.s"
	@echo "... 06-Readdir/06.3-Getdents.o"
	@echo "... 06-Readdir/06.3-Getdents.i"
	@echo "... 06-Readdir/06.3-Getdents.s"
	@echo "... 06-Readdir/06.4-Recursive6.2.o"
	@echo "... 06-Readdir/06.4-Recursive6.2.i"
	@echo "... 06-Readdir/06.4-Recursive6.2.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

