CC = gcc

CFLAGS = -O3 -Wall -Werror -Wextra -Wnarrowing -Wconversion -Wwrite-strings -Wcast-qual -Wundef -Wstrict-prototypes -Wbad-function-cast -Wlogical-op -Wreturn-type

all: 09-Statvfs

09-Statvfs: 
	$(CC) $(CFLAGS) 09-Statvfs.c -o 09-Statvfs.exe