CC = gcc

CFLAGS = -O3 -Wall -Werror -Wextra -Wnarrowing -Wconversion -Wwrite-strings -Wcast-qual -Wundef -Wstrict-prototypes -Wbad-function-cast -Wlogical-op -Wreturn-type

all: 16-MsgQueue

16-MsgQueue:
	$(CC) $(CFLAGS) 16-MsgQueue.c -lrt -o 16-MsgQueue.exe