CC = gcc

CFLAGS = -O3 -Wall -Werror -Wextra -Wnarrowing -Wconversion -Wwrite-strings -Wcast-qual -Wundef -Wstrict-prototypes -Wbad-function-cast -Wlogical-op -Wreturn-type

all: 08-Filefrag

08-Filefrag:
	$(CC) $(CFLAGS) 08-filefrag.c -o 08-filefrag.exe


