CC = gcc

CFLAGS = -O3 -Wall -Werror -Wextra -Wnarrowing -Wconversion -Wwrite-strings -Wcast-qual -Wundef -Wstrict-prototypes -Wbad-function-cast -Wlogical-op -Wreturn-type

all: 19-Threads

19-Threads:
	$(CC) $(CFLAGS) 19.1-Mutex.c -lm -pthread -o 19.1-Mutex.exe