CC = gcc

CFLAGS = -O3 -Wall -Werror -Wextra -Wnarrowing -Wconversion -Wwrite-strings -Wcast-qual -Wundef -Wstrict-prototypes -Wbad-function-cast -Wlogical-op -Wreturn-type

all: 01-Stat

01-Stat:
	$(CC) $(CFLAGS) 01-Stat.c -o 01-Stat.exe