CC = gcc

CFLAGS = -O3 -Wall -Werror -Wextra -Wnarrowing -Wconversion -Wwrite-strings -Wcast-qual -Wundef -Wstrict-prototypes -Wbad-function-cast -Wlogical-op -Wreturn-type

all: 18-dlopen

18-dlopen:
	$(CC) $(CFLAGS) 18-dlopen.c -lm -ldl -o 18-dlopen.exe