CC = gcc

CFLAGS = -O3 -Wall -Werror -Wextra -Wnarrowing -Wconversion -Wwrite-strings -Wcast-qual -Wundef -Wstrict-prototypes -Wbad-function-cast -Wlogical-op -Wreturn-type

all: 10-Inotify

10-Inotify:
	$(CC) $(CFLAGS) 10-Inotify.c -o 10-Inotify.exe
	$(CC) $(CFLAGS) 10-Inotify_CRT_DEL.c -o 10-Inotify_CRT_DEL.exe
